# Generated by Django 5.0.3 on 2024-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('horizontal_resolution', models.FloatField(blank=True, null=True)),
                ('vertical_resolution', models.FloatField(blank=True, null=True)),
                ('bit_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('color_representation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
